Models/ShoppingCart.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Undisclosed_Shop.Models
{
    public class ShoppingCart
    {
        ApplicationDbContext dbContext = new ApplicationDbContext();

        string ShoppingCartId { get; set; }
        public const string CartSessionKey = "CartId";

        // We're using HttpContextBase to allow access to cookies.
        public string GetCartId(HttpContextBase context)
        {
            if (context.Session[CartSessionKey] == null)
            {
                if (!string.IsNullOrWhiteSpace(context.User.Identity.Name))
                {
                    context.Session[CartSessionKey] =
                        context.User.Identity.Name;
                }
                else
                {
                    // Generate a new random GUID using System.Guid class
                    Guid tempCartId = Guid.NewGuid();
                    // Send tempCartId back to client as a cookie
                    context.Session[CartSessionKey] = tempCartId.ToString();
                }
            }
            return context.Session[CartSessionKey].ToString();
        }

        public static ShoppingCart GetCart(HttpContextBase context)
        {
            var cart = new ShoppingCart();
            cart.ShoppingCartId = cart.GetCartId(context);
            return cart;
        }

        // Helper method to simplify shopping cart calls
        public static ShoppingCart GetCart(Controller controller)
        {
            return GetCart(controller.HttpContext);
        }

        //Add To Cart
        public int AddToCart(Products product)
        {
            // Get the matching cart and item instances
            var cartItem = dbContext.Carts.SingleOrDefault(
                c => c.CartId == ShoppingCartId
                && c.ProductId == product.ProductId);

            if (cartItem == null)
            {
                // Create a new cart item if no cart item exists
                cartItem = new Cart
                {
                    ProductId = product.ProductId,
                    CartId = ShoppingCartId,
                    Count = 1,
                    DateCreated = DateTime.Now
                };
                dbContext.Carts.Add(cartItem);
            }
            else
            {
                // If the item does exist in the cart, 
                // then add one to the quantity
                cartItem.Count++;
            }
            // Save changes
            dbContext.SaveChanges();

            return cartItem.Count;
        }

        //Remove From Cart
        public int RemoveFromCart(int id)
        {
            // Get the cart
            var cartItem = dbContext.Carts.Single(
                cart => cart.CartId == ShoppingCartId
                && cart.ProductId == id);


            int itemCount = 0;

            if (cartItem != null)
            {
                if (cartItem.Count > 1)
                {
                    cartItem.Count--;
                    itemCount = cartItem.Count;
                }
                else
                {
                    dbContext.Carts.Remove(cartItem);
                }
                // Save changes
                dbContext.SaveChanges();
            }
            return itemCount;
        }

        //Empty Cart
        public void EmptyCart()
        {
            var cartItems = dbContext.Carts.Where(
                cart => cart.CartId == ShoppingCartId);

            foreach (var cartItem in cartItems)
            {
                dbContext.Carts.Remove(cartItem);
            }
            // Save changes
            dbContext.SaveChanges();
        }

        //Items In Cart
        public int GetCount()
        {
            // Get the count of each item in the cart and sum them up
            int? count = (from cartItems in dbContext.Carts
                          where cartItems.CartId == ShoppingCartId
                          select (int?)cartItems.Count).Sum();
            // Return 0 if all entries are null
            return count ?? 0;
        }

        //Total Cost Of Cart
        public double GetTotal()
        {
            // Multiply item price by count of that item to get 
            // the current price for each of those items in the cart
            // sum all item price totals to get the cart total
            double? total;

            total = (from cartItems in dbContext.Carts
                     where cartItems.CartId == ShoppingCartId
                     select (int?)cartItems.Count *
                     cartItems.Products.ProductPrice).Sum();




            return total ?? double.NaN;
        }

        //Get Cart Items
        public List<Cart> GetCartItems()
        {
            return dbContext.Carts.Where(
                cart => cart.CartId == ShoppingCartId).ToList();
        }

        //Get Cart Items
        public double GetDeliveryFee()
        {
            double deliveryFee = 0;
            int numProducts = 0;

            numProducts = GetCount();

            if (numProducts == 1)
            {
                deliveryFee = 60;
            }
            else if (numProducts <= 3)
            {
                deliveryFee = 80;
            }
            else
            {
                deliveryFee = 100;
            }

            return deliveryFee;
        }

        //Cart Finalize
        public Sale CreateOrder(Sale sale)
        {
            double orderTotal = 0;
            sale.SaleDetails = new List<SaleDetail>();

            var cartItems = GetCartItems();
            // Iterate over the items in the cart, 
            // adding the order details for each
            foreach (var item in cartItems)
            {
                var saleDetail = new SaleDetail()
                {
                    ProductId = item.ProductId,
                    SaleId = sale.SaleId,
                    ProductPrice = item.Products.ProductPrice,
                    Quantity = item.Count,
                };

                // Set the order total of the shopping cart
                orderTotal += (item.Count * item.Products.ProductPrice);
                sale.SaleDetails.Add(saleDetail);
                dbContext.SaleDetails.Add(saleDetail);

            }
            // Set the order's total to the orderTotal count
            sale.SaleTotal = orderTotal;

            // Save the order
            dbContext.SaveChanges();
            // Empty the shopping cart
            EmptyCart();
            // Return the OrderId as the confirmation number
            return sale;
        }


    }
}

Controllers/CheckoutController.cs
//using Undisclosed_Shop.Helpers;
using Undisclosed_Shop.Models;
using Undisclosed_Shop.VeiwModels;
using Microsoft.AspNet.Identity.Owin;
using Syncfusion.Pdf;
using Syncfusion.Pdf.Graphics;
using Syncfusion.Pdf.Grid;
using System;
using System.Collections.Generic;
using System.Data;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Text;
using System.Web;
using System.Web.Mvc;

namespace Undisclosed_Shop.Controllers
{
    public class CheckoutController : Controller
    {
        ApplicationDbContext dB = new ApplicationDbContext();
        private ApplicationSignInManager _signInManager;
        private ApplicationUserManager _userManager;
        string[] cmt = { "Excellent", "Good experience", "Satisfactory service", "Amazing Book" };
        int[] rt = { 5, 4, 3, 2, 1 };
        public CheckoutController()
        {
        }

        public CheckoutController(ApplicationUserManager userManager, ApplicationSignInManager signInManager)
        {
            UserManager = userManager;
            SignInManager = signInManager;
        }

        public ApplicationSignInManager SignInManager
        {
            get
            {
                return _signInManager ?? HttpContext.GetOwinContext().Get<ApplicationSignInManager>();
            }
            private set
            {
                _signInManager = value;
            }
        }

        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }
        // GET: Checkout
        public ActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public ActionResult Payment()
        {
            var viewModel = new ShoppingCartViewModel();
            try
            {

                var cart = ShoppingCart.GetCart(this.HttpContext);
                if (cart.GetCartItems().Count() > 0)
                {
                    viewModel = new ShoppingCartViewModel()
                    {
                        CartItems = cart.GetCartItems(),
                        CartTotal = cart.GetTotal()
                    };

                    ViewBag.TotalCost = cart.GetTotal() + cart.GetDeliveryFee();
                    ViewBag.ShippingCost = cart.GetDeliveryFee();
                    return View(viewModel);
                }
                else
                {
                    return RedirectToAction("OurProducts", "Products");
                }
                // Set up our ViewModel

            }
            catch (Exception)
            {
                return RedirectToAction("OurProducts", "Products");
                //   throw;
            }

            // Return the view
            return View(viewModel);
        }
        [Authorize]
        [HttpPost]
        public ActionResult Payment([Bind(Include = "Name,City,State,PostalCode,Email,Id,Address")] ApplicationUser applicationUser, ShoppingCartViewModel shpVM) //The Method That Handles All Transactions
        {
            var FindPaymentMethods = dB.PaymentMethods;

            //Variables Required For Tables
            double deliveryFee = 0;
            int numProducts = 0;

            //Get Current Cart
            var cart = ShoppingCart.GetCart(this.HttpContext);

            //Create New Sale
            Sale sale = new Sale();
            sale.SaleDate = DateTime.Now.ToString();


            numProducts = cart.GetCount();

            if (numProducts == 1)
            {
                deliveryFee = 60;
            }
            else if (numProducts <= 3)
            {
                deliveryFee = 80;
            }
            else
            {
                deliveryFee = 100;
            }



            //Customer Details
            var getUsers = dB.Users.Where(v => v.Id != null).ToList();

            //Customer Details
            foreach (var user in getUsers)
            {
                sale.Email = User.Identity.Name;
                sale.Name = user.Name;
                sale.Address = user.Address;
                sale.City = user.City;
                sale.State = user.State;
                sale.PostalCode = user.PostalCode;
                sale.Country = user.Country;
                sale.PhoneNumber = user.PhoneNumber;
            }

            //var Discount = dB.UsedCouponLists.Where(s => s.userId == sale.Email);

            //  //Sale Total
            //  if (Discount.Any())
            //  {
            //      foreach (var discount in Discount)
            //      {
            //          if (discount.CouponDiscountAmount != null)
            //          {
            //              double? SaleFinal = cart.GetTotal() - (cart.GetTotal() * discount.CouponDiscountAmount) / 100;
            //              sale.SaleTotal = SaleFinal + deliveryFee;
            //              sale.Paid = true;
            //          }
            //      }
            //  }
            //  else
            //  {
            //      double SaleFinal = cart.GetTotal();
            //      sale.SaleTotal = SaleFinal + deliveryFee;
            //      sale.Paid = true;
            //  }

            //  Check product stock
            var x = cart.GetCartItems();
            List<Products> chck = (from q in dB.Products
                                   select q).ToList();
            //if (x.Count() > 0)
            //{
            //    foreach (var items in x)
            //    {
            //        if (chck.Count() > 0)
            //            foreach (Products c in chck)
            //            {
            //                if (items.ProductId == c.ProductId)
            //                {
            //                    Random random = new Random();
            //                    int start2 = random.Next(0, cmt.Length);

            //                    var addAna = AnalyticsHelper.Insert(c.ProductName, c.ProductDescription, cmt[start2].ToString(), rt[start2]);

            //                    c.ProductStock -= items.Count; //Temporary stock check pause... Make this -= to reduce stock
            //                    if (c.ProductStock == 0)
            //                    {
            //                        c.isActive = false; //Sets item to inactive due to stock being zero. 
            //                    }
            //                }
            //            }
            //    }
            //}


            //  Save Order to Delivery and Sale Table
            Delivery delivery = new Delivery
            {
                SaleId = sale.SaleId,
                DeliveryFee = deliveryFee,
                CurrentLocation = "131 George Sewpersadh St, Verulam, Ethekwini, 4340",
                isDelivered = false
            };
            dB.Sales.Add(sale);
            dB.SaveChanges();
           // delivery.SaleId = sale.SaleId;
            sale.Dispatched = false;
            sale.ConfirmOrder = null;
            sale.ConfirmDelivery = false;
            //dB.Deliveries.Add(delivery);




            //double? FinalCost;
            double? FinalCost = cart.GetTotal() + cart.GetDeliveryFee();

            //if (Discount.Any())
            //{
            //    foreach (var discount in Discount)
            //    {
            //        if (discount.CouponDiscountAmount != null)
            //        {
            //            FinalCost = cart.GetTotal() - (cart.GetTotal() * discount.CouponDiscountAmount) / 100 + cart.GetDeliveryFee();
            //        }
            //        if (discount.CouponUserIsValid == true)
            //        {
            //            discount.CouponUserIsValid = false;
            //            discount.Coupon.CouponCounter = +1;
            //        }
            //    }
            //}
            dB.SaveChanges();



            //SaleDetail Saved Using Helper Method
            string orderId = sale.SaleId.ToString();
            sale = cart.CreateOrder(sale);

            //New Email.
            //Creates a new PDF document
            PdfDocument document = new PdfDocument();
            //Adds page settings
            document.PageSettings.Orientation = PdfPageOrientation.Portrait;
            document.PageSettings.Margins.All = 50;
            //Adds a page to the document
            PdfPage page = document.Pages.Add();
            PdfGraphics graphics = page.Graphics;
            //Loads the image from disk
            PdfImage image = PdfImage.FromFile(Server.MapPath("~/Content/Images/Evetech.jpeg"));
            RectangleF bounds = new RectangleF(10, 10, 200, 200);
            //Draws the image to the PDF page
            page.Graphics.DrawImage(image, bounds);
            PdfBrush solidBrush = new PdfSolidBrush(new PdfColor(126, 151, 173));
            bounds = new RectangleF(0, bounds.Bottom + 90, graphics.ClientSize.Width, 30);
            //Draws a rectangle to place the heading in that region.
            graphics.DrawRectangle(solidBrush, bounds);
            //Creates a font for adding the heading in the page
            PdfFont subHeadingFont = new PdfStandardFont(PdfFontFamily.TimesRoman, 14);
            //Creates a text element to add the invoice number
            PdfTextElement element = new PdfTextElement("Invoice " + sale.SaleId.ToString() + " for" + " " + sale.Name, subHeadingFont);
            element.Brush = PdfBrushes.White;

            //Draws the heading on the page
            PdfLayoutResult res = element.Draw(page, new PointF(10, bounds.Top + 8));
            string currentDate = "Date Purchased " + sale.SaleDate.ToString();
            //Measures the width of the text to place it in the correct location
            SizeF textSize = subHeadingFont.MeasureString(currentDate);

Views/ShoppingCart/CartSummary.cshtml
<a href='@Url.Action("Index", "ShoppingCart")'><strong>Cart</strong>  <span id="cart-status" class="badge">@ViewData["CartCount"]</span></a>

Views/ShoppingCart/DetailsCon.cshtml
@model Undisclosed_Shop.VeiwModels.ShoppingCartViewModel
@{
    ViewBag.Title = "Shopping Cart";
}


<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
<script type="text/javascript">
    $(function () {
        // Document.ready -> link up remove event handler
        $(".RemoveLink").click(function () {
            // Get the id from the link
            var recordToDelete = $(this).attr("data-id");
            if (recordToDelete != '') {
                // Perform the ajax post
                $.post("/ShoppingCart/RemoveFromCart", { "id": recordToDelete },
                    function (data) {
                        // Successful requests get here
                        // Update the page elements
                        if (data.ItemCount == 0) {
                            $('#row-' + data.DeleteId).fadeOut('slow');
                        } else {
                            $('#item-count-' + data.DeleteId).text(data.ItemCount);
                        }
                        $('#cart-total').text(data.CartTotal);
                        $('#update-message').text(data.Message);
                        $('#cart-status').text(data.CartCount);
                    });
            }
        });
    });
</script>
<h3 class="text-center text-success">
    <em>Review</em> your cart:
</h3>



@{

    if (Model.CartItems.Count > 0)
    {
        <div class="panel panel-info">
            <div class="panel-heading">
                <h3 class="panel-title">Order Summary</h3>
            </div>
            <div class="panel-body">

                <div id="update-message">
                </div>
                <table class="table table-striped table-hover ">
                    <thead>
                        <tr>
                            <th>
                                Products:
                            </th>
                            <th>
                                Price:
                            </th>
                            <th>
                                Quantity:
                            </th>
                            <th></th>
                        </tr>
                    </thead>
                    @foreach (var item in Model.CartItems)
                    {
                        <tr id="row-@item.ProductId">
                            <td>
                                @Html.ActionLink(item.Products.ProductName, "Details", "Products", new { id = item.ProductId }, null)
                            </td>
                            <td>
                                &#82;@item.Products.ProductPrice
                            </td>
                            <td id="item-count-@item.ProductId">
                                @item.Count
                            </td>
                            <td>
                                <a href="#" class="AddLink"
                                   data-id="@item.ProductId">
                                    Remove
                                    from cart
                                </a>
                            </td>
                        </tr>
                    }
                    <tr>
                        <td>
                            Total
                        </td>
                        <td></td>
                        <td></td>
                        <td id="cart-total">
                            &#82;@Model.CartTotal
                        </td>
                    </tr>
                    <tr>
                        <td>
                            Shipping Fee
                        </td>
                        <td></td>
                        <td></td>
                        <td id="cart-total">
                            &#82;@ViewBag.ShippingCost
                        </td>
                    </tr>
                    <tr>
                        <td>
                            Total Including Shipping
                        </td>
                        <td></td>
                        <td></td>
                        <td id="cart-total">
                            <strong>&#82;@ViewBag.TotalCost</strong>
                        </td>
                    </tr>
                    <tfoot>Please ensure that all products in cart are correct before checking out.</tfoot>
                </table>
                <button type="button" class="dropbtn" onclick="location.href='@Url.Action("Payment", "Checkout")'">
                    Confirm and Pay &#82;@ViewBag.TotalCost
                </button>
            </div>
        </div>

    }
    else
    {
        <div>
            <p>
                There are no items in your cart currently. Please shop for something and add items..
            </p>
        </div>
    }
}

Views/ShoppingCart/Index.cshtml
@model Undisclosed_Shop.VeiwModels.ShoppingCartViewModel
@{
    ViewBag.Title = "Shopping Cart";
}

<style>
    body {
        margin-left: 40px;
        margin-right: 40px;
    }
</style>

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
<script type="text/javascript">$(function () {
        // Document.ready -> link up remove event handler
        $(".RemoveLink").click(function () {
            // Get the id from the link
            var recordToDelete = $(this).attr("data-id");
            if (recordToDelete != '') {
                // Perform the ajax post
                $.post("/ShoppingCart/RemoveFromCart", { "id": recordToDelete },
                    function (data) {
                        // Successful requests get here
                        // Update the page elements
                        if (data.ItemCount == 0) {
                            $('#row-' + data.DeleteId).fadeOut('slow');
                        } else {
                            $('#item-count-' + data.DeleteId).text(data.ItemCount);
                        }
                        $('#cart-total').text(data.CartTotal);
                        $('#update-message').text(data.Message);
                        $('#cart-status').text(data.CartCount);
                    });
            }
        });
    });</script>
<h3 class="text-center text-success">
    <em>Review</em> your cart:
</h3>



@{

    if (Model.CartItems.Count > 0)
    {
        <div class="panel panel-info">
            <div class="panel-heading">
                <h3 class="panel-title">Order Summary</h3>
            </div>
            <div class="panel-body">

                <div id="update-message">
                </div>
                <table class="table table-striped table-hover ">
                    <thead>
                        <tr>
                            <th>
                                Products:
                            </th>
                            <th>
                                Price:
                            </th>
                            <th>
                                Quantity:
                            </th>
                            <th></th>
                        </tr>
                    </thead>
                    @foreach (var item in Model.CartItems)
                    {
                        <tr id="row-@item.ProductId">
                            <td class="pro-field">
                                @Html.ActionLink(item.Products.ProductName, "Details", "Products", new { id = item.ProductId, @class = "pro-field" }, null)
                            </td>
                            <td>
                                &#82;@item.Products.ProductPrice
                            </td>
                            <td id="item-count-@item.ProductId">
                                @item.Count
                            </td>
                            <td class="remove-cart">
                                <a href="~/ShoppingCart" class="RemoveLink"
                                   data-id="@item.ProductId">
                                    Remove
                                </a>
                            </td>
                        </tr>
                    }
                    <tr>
                        <td>
                            Total
                        </td>
                        <td></td>
                        <td></td>
                        <td id="cart-total">
                            &#82;@Model.CartTotal
                        </td>
                    </tr>
                    <tr>
                        <td>
                            Shipping Fee
                        </td>
                        <td></td>
                        <td></td>
                        <td id="cart-total">
                            &#82;@ViewBag.ShippingCost
                        </td>
                    </tr>
                    @if (ViewBag.Discount != null)
                    {
                        <tr>
                            <td>
                                Discount for total
                            </td>
                            <td></td>
                            <td></td>
                            <td id="cart-total">
                                @ViewBag.Discount%
                            </td>
                        </tr>
                    }
                    <tr>
                        <td>
                            Total Including Shipping
                        </td>
                        <td></td>
                        <td></td>
                        <td id="cart-total">
                            <strong>&#82;@ViewBag.TotalCost</strong>
                        </td>
                    </tr>



                    <tfoot>Please ensure that all products in cart are correct before checking out.</tfoot>
                </table>

                @TempData["Result"]

                <button type="button" style="color:black; margin-bottom:10px; cursor:pointer;" class="dropbtn" onclick="location.href='@Url.Action("Payment", "Checkout")'">
                    Confirm and Pay &#82;@ViewBag.TotalCost
                </button>
                <button type="button" style="color:black; margin-bottom:10px; cursor:pointer;" class="dropbtn" onclick="location.href='@Url.Action("Create", "UsedCouponLists")'">
                    Enter coupon
                </button>
            </div>
        </div>

    }
    else
    {
        <div>
            <p>
                There are no items in your cart currently. Please shop for something and add items..
            </p>
        </div>
    }
}
<style>
    .pro-field a {
        color: black;
        font-weight: bold;
    }

    .remove-cart a {
        color: white;
        padding: 4px 10px;
        background: red;
        border-radius: 2px;
    }
</style> 