Models/Products.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Undisclosed_Shop.Models
{
    public class Products
    {

        [Key]
        public int ProductId { get; set; }

        [Required]
        public string ProductName { get; set; }

        [Required]
        public int ProductStock { get; set; }

        [Required]
        public double ProductPrice { get; set; }

        [Required]
        public string ProductDescription { get; set; }

        [Required]
        public string ProductCategory { get; set; }

        public string ProductImage { get; set; }


    }
}

Controllers/ProductsController.cs
using Microsoft.AspNet.Identity;
using PagedList;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.SqlClient;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;
using Undisclosed_Shop.Models;

namespace Undisclosed_Shop.Controllers
{
    public class ProductsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Products
        // GET: Products
        public ActionResult Index(string searchString, string sortOrder)
        {
            // Store the current sort order and search string in ViewBag
            ViewBag.CurrentSort = sortOrder;
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewBag.PriceSortParm = sortOrder == "Price" ? "price_desc" : "Price";
            ViewBag.CategorySortParm = sortOrder == "Category" ? "category_desc" : "Category";

            // Get all products from the database
            var products = from p in db.Products
                           select p;

            // Apply the search filter if any
            if (!String.IsNullOrEmpty(searchString))
            {
                products = products.Where(p => p.ProductName.Contains(searchString)
                                            || p.ProductDescription.Contains(searchString)
                                            || p.ProductCategory.Contains(searchString));
            }

            // Apply the sort order if any
            switch (sortOrder)
            {
                case "name_desc":
                    products = products.OrderByDescending(p => p.ProductName);
                    break;
                case "Price":
                    products = products.OrderBy(p => p.ProductPrice);
                    break;
                case "price_desc":
                    products = products.OrderByDescending(p => p.ProductPrice);
                    break;
                case "Category":
                    products = products.OrderBy(p => p.ProductCategory);
                    break;
                case "category_desc":
                    products = products.OrderByDescending(p => p.ProductCategory);
                    break;
                default:
                    products = products.OrderBy(p => p.ProductName);
                    break;
            }

            // Return the view with the filtered and sorted products
            return View(products.ToList());
        }
        public ActionResult UserProducts(string sortOrder, string currentFilter, string searchString, int? page) 
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewBag.PriceSortParm = sortOrder == "Price" ? "price_desc" : "Price";

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;

            var items = from i in db.Products
                        select i;
            if (!String.IsNullOrEmpty(searchString))
            {
                items = items.Where(s => s.ProductName.ToUpper().Contains(searchString.ToUpper())
                                       || s.ProductCategory.ToUpper().Contains(searchString.ToUpper()));
            }
            switch (sortOrder)
            {
                case "name_desc":
                    items = items.OrderByDescending(s => s.ProductName);
                    break;
                case "Price":
                    items = items.OrderBy(s => s.ProductPrice);
                    break;
                case "price_desc":
                    items = items.OrderByDescending(s => s.ProductPrice);
                    break;
                default:  // Sort By Name ASC
                    items = items.OrderBy(s => s.ProductName);
                    break;
            }

            int pageSize = 7;
            int pageNumber = (page ?? 1);
            return View(items.ToPagedList(pageNumber, pageSize));
        }

        // GET: Products/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Products products = db.Products.Find(id);
            if (products == null)
            {
                return HttpNotFound();
            }
            return View(products);
        }

        // GET: Products/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Products/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ProductId,ProductName,ProductStock,ProductPrice,ProductDescription,ProductCategory")] Products products, HttpPostedFileBase image)
        {
            if (ModelState.IsValid)
            {
                if (image != null && image.ContentLength > 0)
                {
                    var fileName = Path.GetFileName(image.FileName);
                    var path = Path.Combine(Server.MapPath("~/ProductImages/"), fileName);
                    image.SaveAs(path);

                    products.ProductImage = fileName;
                }

                db.Products.Add(products);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(products);
        }

        // GET: Products/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Products products = db.Products.Find(id);
            if (products == null)
            {
                return HttpNotFound();
            }
            return View(products);
        }

        // POST: Products/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, [Bind(Include = "ProductId,ProductName,ProductStock,ProductPrice,ProductDescription,ProductCategory")] Products products, HttpPostedFileBase image)
        {
            if (ModelState.IsValid)
            {
                if (image != null && image.ContentLength > 0)
                {
                    var fileName = Path.GetFileName(image.FileName);
                    var path = Path.Combine(Server.MapPath("~/ProductImages/"), fileName);
                    image.SaveAs(path);

                    products.ProductImage = fileName;
                }

                db.Entry(products).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(products);
        }

        // GET: Products/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Products products = db.Products.Find(id);
            if (products == null)
            {
                return HttpNotFound();
            }
            return View(products);
        }

        // POST: Products/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Products products = db.Products.Find(id);
            db.Products.Remove(products);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }



    }
}

Controllers/ShopingCartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Undisclosed_Shop.Models;
using Undisclosed_Shop.VeiwModels;

namespace Undisclosed_Shop.Controllers
{
        [Authorize]
        public class ShoppingCartController : Controller
        {
            ApplicationDbContext dB = new ApplicationDbContext();


            // GET: ShoppingCart
            public ActionResult Index()
            {
                var cart = ShoppingCart.GetCart(this.HttpContext);

                // Set up our ViewModel


                var viewModel = new ShoppingCartViewModel()
                {

                    CartItems = cart.GetCartItems(),
                    CartTotal = cart.GetTotal()

                };

                ViewBag.TotalCost = cart.GetTotal() + cart.GetDeliveryFee();
                ViewBag.ShippingCost = cart.GetDeliveryFee();

                // Return the view
                return View(viewModel);
            }

            //Add To Cart
            [HttpPost]

            public ActionResult AddToCart(int id)
            {
                // Retrieve the item from the database
                var addedItem = dB.Products
                    .Single(products => products.ProductId == id);

                var test = addedItem.ProductName;
                // Add it to the shopping cart
                var cart = ShoppingCart.GetCart(this.HttpContext);

                int count = cart.AddToCart(addedItem);


                var results = new ShoppingCartRemoveViewModel
                {
                    Message = Server.HtmlEncode(addedItem.ProductName) +
                        " has been added to your shopping cart.",
                    CartTotal = cart.GetTotal(),
                    CartCount = cart.GetCount(),
                    ItemCount = count,
                    DeleteId = id
                };
                return Json(results);
            }
            //End

            //Remove From Cart
            [HttpPost]
            public ActionResult RemoveFromCart(int id)
            {
                // Remove the item from the cart
                var cart = ShoppingCart.GetCart(this.HttpContext);

                // Get the name of the item to display confirmation

                // Get the name of the album to display confirmation
                string itemName = dB.Products
                    .Single(item => item.ProductId == id).ProductName;

                // Remove from cart
                int itemCount = cart.RemoveFromCart(id);

                // Display the confirmation message
                var results = new ShoppingCartRemoveViewModel
                {
                    Message = "One (1) " + Server.HtmlEncode(itemName) +
                        " has been removed from your shopping cart.",
                    CartTotal = cart.GetTotal(),
                    CartCount = cart.GetCount(),
                    ItemCount = itemCount,
                    DeleteId = id
                };
                return Json(results);
            }
            //End

            // GET: /ShoppingCart/CartSummary
            [ChildActionOnly]
            public ActionResult CartSummary()
            {
                var cart = ShoppingCart.GetCart(this.HttpContext);

                ViewData["CartCount"] = cart.GetCount();
                return PartialView("CartSummary");
            }


            // GET: ShoppingCart/Details/5
            public ActionResult Details(int id)
            {
                return View();
            }

            // GET: ShoppingCart/Create
            public ActionResult Create()
            {
                return View();
            }

            // POST: ShoppingCart/Create
            [HttpPost]
            public ActionResult Create(FormCollection collection)
            {
                try
                {
                    // TODO: Add insert logic here

                    return RedirectToAction("Index");
                }
                catch
                {
                    return View();
                }
            }

            // GET: ShoppingCart/Edit/5
            public ActionResult Edit(int id)
            {
                return View();
            }

            // POST: ShoppingCart/Edit/5
            [HttpPost]
            public ActionResult Edit(int id, FormCollection collection)
            {
                try
                {
                    // TODO: Add update logic here

                    return RedirectToAction("Index");
                }
                catch
                {
                    return View();
                }
            }

            // GET: ShoppingCart/Delete/5
            public ActionResult Delete(int id)
            {
                return View();
            }

            // POST: ShoppingCart/Delete/5
            [HttpPost]
            public ActionResult Delete(int id, FormCollection collection)
            {
                try
                {
                    // TODO: Add delete logic here

                    return RedirectToAction("Index");
                }
                catch
                {
                    return View();
                }
            }
            public ActionResult DetailsCon()
            {
                var cart = ShoppingCart.GetCart(this.HttpContext);

                // Set up our ViewModel
                var viewModel = new ShoppingCartViewModel()
                {
                    CartItems = cart.GetCartItems(),
                    CartTotal = cart.GetTotal()
                };

                ViewBag.TotalCost = cart.GetTotal() + cart.GetDeliveryFee();
                ViewBag.ShippingCost = cart.GetDeliveryFee();
                // Return the view
                return View(viewModel);
            }
        }
    
}

Views/Products/Create.cshtml
@model Undisclosed_Shop.Models.Products

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Create</title>
</head>
<body>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")

    @using (Html.BeginForm("Create", "Products", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>Products</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.ProductName, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.ProductName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ProductName, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.ProductStock, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.ProductStock, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ProductStock, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.ProductPrice, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.ProductPrice, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ProductPrice, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.ProductDescription, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.ProductDescription, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ProductDescription, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.ProductCategory, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.ProductCategory, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ProductCategory, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.ProductImage, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <input type="file" name="image" />
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</body>
</html>

Views/Products/Delete.cshtml
@model Undisclosed_Shop.Models.Products

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Delete</title>
</head>
<body>
    <h3>Are you sure you want to delete this?</h3>
    <div>
        <h4>Products</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.ProductName)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.ProductName)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.ProductStock)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.ProductStock)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.ProductPrice)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.ProductPrice)
            </dd>
    
        </dl>
    
        @using (Html.BeginForm()) {
            @Html.AntiForgeryToken()
    
            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-default" /> |
                @Html.ActionLink("Back to List", "Index")
            </div>
        }
    </div>
</body>
</html>

Views/Products/Details.cshtml
@model Undisclosed_Shop.Models.Products

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Details</title>
</head>
<body>
    <div>
        <h4>Products</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.ProductName)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.ProductName)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.ProductStock)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.ProductStock)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.ProductPrice)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.ProductPrice)
            </dd>
    
        </dl>
    </div>
    <p>
        @Html.ActionLink("Edit", "Edit", new { id = Model.ProductId }) |
        @Html.ActionLink("Back to List", "Index")
    </p>
</body>
</html>

Views/Products/Edit.cshtml
@model Undisclosed_Shop.Models.Products

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Edit</title>
</head>
<body>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")


    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>Products</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.ProductId)

            <div class="form-group">
                @Html.LabelFor(model => model.ProductName, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.ProductName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ProductName, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.ProductStock, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.ProductStock, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ProductStock, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.ProductPrice, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.ProductPrice, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ProductPrice, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.ProductCategory, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.ProductCategory, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ProductCategory, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.ProductDescription, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.ProductDescription, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ProductDescription, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</body>
</html>

Views/Products/UserProducts.cshtml
@model PagedList.IPagedList<Undisclosed_Shop.Models.Products>
@using PagedList.Mvc

@{
    Layout = "~/Views/Shared/_Layout.cshtml";

}
<link href="~/Content/PagedList.css" rel="stylesheet" />
<link href="~/Content/themeassets/css/UserProduct.css" rel="stylesheet" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.2/css/all.min.css" />
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

<!DOCTYPE html>

<head>
    <meta name="viewport" content="width=device-width" />
    <title>UserProducts</title>
</head>

<style>
    .fa-heart {
        background-color: #8a2be2;
    }

    .scrollable-container {
        overflow-y: auto;
        height: 100vh; /* Set the height to fill the viewport */
        padding: 20px; /* Add padding as needed */
    }
</style>

<script type="text/javascript">
    $(document).ready(function () {
        $(".AddLink").click(function (event) {
            event.preventDefault(); // Prevent the default action of the anchor tag

            var productId = $(this).data("id"); // Get the product ID from the data-id attribute

            $.post("/ShoppingCart/AddToCart", { id: productId })
                .done(function (data) {
                    $('#cart-status').text(data.CartCount); // Update cart count
                })
                .fail(function (xhr, status, error) {
                    console.error(xhr.responseText); // Log any errors to the console
                });
        });
    });
</script>

<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">

    <div aria-hidden="true" class="alert alert-dismissable alert-success">
        <button type="button" class="close" data-dismiss="alert">×</button>
        <strong>An item was added to your cart.</strong> To check out now simply <a href="#" class="alert-link">click here</a>.
    </div>

    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                @*<h4 class="modal-title">Confirm check out.</h4>*@
            </div>
            <div class="modal-body">
                <p>Are you sure you want to checkout?</p>

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Keep Shopping</button>
                <button type="submit" class="btn btn-primary" onclick="location.href='@Url.Action("Index", "ShoppingCart")'">Check Out</button>
            </div>
        </div>
    </div>
</div>

<body>
    <div class="scrollable-container">
        @if (Model != null && Model.Any())
        {
            foreach (var item in Model)
            {
                <div class="card1-columns px-3">
                    @{

                        ViewBag.ProductId = item.ProductId;
                        ViewBag.ProductName = item.ProductName;


                    }

                    <div class="column1 d-flex justify-content-center p-3">
                        <div class="grid1-container px-4" style="box-shadow: 0 4px 3px black; background:rgb(245, 245, 245);border-radius:4px">
                            <div class="grid1-item">

                                <div class="card1 .center">
                                    <div class="card1-img .center">
                                        <img src="@Url.Content("~/ProductImages/" + item.ProductImage)"
                                             style="width:300px; height:300px; margin:0px; padding:10px" alt="no photo" class="adsm-image; center-url" />
                                    </div>

                                    <div class="card1-body">
                                        <h4 class="card1-title">Name: <span class="card-value">@item.ProductName</span> </h4>
                                    </div>

                                    <div class="card1-body">
                                        <h4 class="card1-title">Price: <span class="card-value">R @item.ProductPrice</span></h4>
                                    </div>
                                    <div class="card1-body d-flex justify-content-center">
                                        <div class="d-flex p-0 pb-1">
                                            @* <span class="m-0 p-0" style="cursor: pointer" id="IncrsQty" onclick="IncrsQty()">
                    <i class="fa fa-plus"></i>
                </span>*@ @*if (item.ProductCategory != 11)
                {
                    <h4 class="m-0 p-0 mx-3" id="quantity">Available Currently<span class="card-value"> @item.ProductStock </span></h4>
                }*@
                                @*<span class="m-0 p-0" id="DecrsQty" onclick="DecrsQty()">
        <i class="fa fa-minus" style="cursor: pointer"></i>
    </span>*@
                                </div>
                                </div>

                                <div class="card1-footer">
                                    <div class="dropdown">

                                        <input type="button" id="btnShowMore" class="dropbtn" onclick="showDesFunction('@item.ProductDescription')" value="Show More">
                                        <div id="Textbox" class="dropdown-content">


                                        </div>

                                    </div>
                                </div>


                                <div class="d-flex justify-content-center pt-2">
                                    <a href="#" class="AddLink AddLinkTab" data-id="@item.ProductId" data-toggle="modal" data-target="#myModal">
                                        <i class="fa fa-cart-plus" aria-hidden="true"></i>
                                    </a>
                                </div>

                                @using (Html.BeginForm("Create", "SavedProducts", FormMethod.Post))
                                {
                                    @Html.Hidden("ProductId", (object)ViewBag.ProductId)
                                    @Html.Hidden("ProductName", (object)ViewBag.ProductName)

                                    <button type="submit" class="fa fa-heart" value="Submit"></button>
                                }

                                </div>
                                </div>
                            </div>
                        </div>
                    </div>

                }
            }
    </div>
</body>